# Generated by Django 6.0.7 on 2026-07-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
