# Generated by Django 6.0.7 on 2026-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_patient_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
