# Generated by Django 6.0.7 on 2026-07-14 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='appointment_time',
            new_name='admit_time',
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
