# Generated by Django 6.0.7 on 2026-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_appointment_time_patient_admit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='discharge_time',
            field=models.TimeField(null=True),
        ),
    ]
