# Generated by Django 6.0.7 on 2026-07-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_registermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterModel',
        ),
    ]
