# Generated by Django 6.0.7 on 2026-07-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_patient_discharge_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='Patient_name',
        ),
    ]
