# Generated by Django 6.0.7 on 2026-07-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_name_patient_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
