# Generated by Django 6.0.7 on 2026-07-16 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_patient_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admit_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discharge_time',
        ),
        migrations.AddField(
            model_name='patient',
            name='admit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_date',
            field=models.DateTimeField(null=True),
        ),
    ]
