# Generated by Django 6.0.7 on 2026-07-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_patient_admit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admit_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discharge_date',
            field=models.DateField(null=True),
        ),
    ]
