# Generated by Django 6.0.7 on 2026-07-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date', models.DateField()),
                ('department', models.CharField(choices=[('General', 'General'), ('Cardiology', 'Cardiology'), ('Gynaecology & Maternity', 'Gynaecology & Maternity'), ('Pediatrics', 'Pediatrics'), ('Orthopaedics', 'Orthopaedics'), ('General Medicine', 'General Medicine'), ('General Surgery', 'General Surgery'), ('Other', 'Other')], max_length=100)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
