# Generated by Django 6.0.7 on 2026-07-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentModel',
        ),
    ]
