# Generated by Django 6.0.7 on 2026-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hopitalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_service', models.IntegerField()),
                ('expert_doctors', models.IntegerField()),
                ('patients_treates', models.IntegerField()),
                ('departments', models.IntegerField()),
            ],
        ),
    ]
