# Generated by Django 6.0.7 on 2026-07-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_hopitalstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hopitalstats',
            old_name='patients_treates',
            new_name='patients_treated',
        ),
    ]
