# Generated by Django 6.0.7 on 2026-07-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_patients_treates_hopitalstats_patients_treated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story_discription',
            new_name='story_description',
        ),
    ]
