# Generated by Django 6.0.7 on 2026-07-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('doctor_specialist', models.CharField(max_length=20)),
                ('doctor_experience', models.TextField()),
            ],
        ),
    ]
