# Generated by Django 6.0.7 on 2026-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctor_img',
            field=models.ImageField(default=12, upload_to='doctors/'),
            preserve_default=False,
        ),
    ]
