# Generated by Django 6.0.7 on 2026-07-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_doctor_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='doctor_img',
        ),
    ]
