# Generated by Django 6.0.7 on 2026-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctors_doctor_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctor_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
