# Generated by Django 6.0.7 on 2026-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctors_created_at_doctors_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
